font_family JetBrainsMono Nerd Font
font_size 12

background_opacity 0.50

confirm_os_window_close 0

cursor_shape beam

enable_audio_bell no

window_padding_width 10

dynamic_background_opacity yes

foreground #f2f2f2
background #111111

selection_foreground #111111
selection_background #d0d0d0

cursor #ff3200
cursor_text_color background

color0  #202020
color8  #606060

color1  #ff3200
color9  #ff5a2a

color2  #9f9f9f
color10 #c5c5c5

color3  #d4a15a
color11 #f1c27d

color4  #909090
color12 #b8b8b8

color5  #7c7c7c
color13 #a0a0a0

color6  #b0b0b0
color14 #d0d0d0

color7  #f2f2f2
color15 #ffffff