
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output = "DP-3",
    mode = "1920x1080@75",
    position = "0x0",
    scale = 1,
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@100",
    position = "0x1080",
    scale = 1,
    transform = 2
})

---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "fuzzel"
local liveWallpaper =
    "/home/3ty6six7/Pictures/Wallpapers/live/miyabi-looking-up-at-the-gray-sky-zenless-zone-zero-moewalls-com.mp4"
local toggleWaybarCmd = [[
    bash -lc '
        if pgrep -x waybar >/dev/null; then
            pkill -x waybar
        else
            waybar >/tmp/waybar.log 2>&1 &
        fi
    '
]]
local liveWallpaperCmd =
    'mpvpaper ALL "' .. liveWallpaper ..
    '" -o "no-audio loop-file=inf hwdec=auto"'
local systemDashboard = [[
    bash -lc '
        # Không dựng cây Dwindle trước khi Waybar reserve màn hình
        for i in $(seq 1 100); do
            if hyprctl layers -j | grep -qi "waybar"; then
                sleep 0.30
                break
            fi

            sleep 0.03
        done

        window_exists() {
            hyprctl clients -j |
                grep -q "\"class\": \"$1\""
        }

        wait_window() {
            class="$1"

            for i in $(seq 1 100); do
                window_exists "$class" && return 0
                sleep 0.02
            done

            return 1
        }

        focus_window() {
            class="$1"

            for i in $(seq 1 50); do
                hyprctl dispatch focuswindow "class:^${class}$" >/dev/null

                hyprctl activewindow -j |
                    grep -q "\"class\": \"${class}\"" &&
                    return 0

                sleep 0.02
            done

            return 1
        }

kitty --class sys-fastfetch --title Fastfetch \
    zsh -lc "clear; fastfetch; echo; ~/.config/hypr/scripts/sysinfo-panel.sh; exec zsh" &
    
        wait_window "sys-fastfetch"
        focus_window "sys-fastfetch"
        hyprctl dispatch layoutmsg "preselect r" >/dev/null

        kitty --class sys-yazi --title Yazi -e yazi &

        wait_window "sys-yazi"
        focus_window "sys-yazi"
        hyprctl dispatch layoutmsg "preselect d" >/dev/null

        kitty --class sys-peaclock --title Peaclock -e peaclock &

        wait_window "sys-peaclock"
        focus_window "sys-fastfetch"
    '
]]
    
-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

hl.on("hyprland.start", function()
    -- Core session
    hl.exec_cmd("playerctld daemon")
    hl.exec_cmd("hyprctl setcursor Bibata-Morden-Ice 30")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("fcitx5")

    -- Desktop
    -- hl.exec_cmd(liveWallpaperCmd)
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("waybar")
    hl.exec_cmd("dunst")

    -- System
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("hypridle")

    -- Startup dashboard
    -- hl.exec_cmd("hyprlock")
    hl.exec_cmd(systemDashboard)
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgba(c80000d9)", "rgba(ff9600d9)"}, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})


-----------------------
------ ANIMATION ------
-----------------------

-- 93-VS Motion Engine
-- Fast, restrained window motion + chainable workspace swipes.

-- Quick ease-out for windows and UI layers.
hl.curve("vs_snap", {
    type = "bezier",
    points = {
        { 0.16, 1.00 },
        { 0.30, 1.00 },
    },
})

-- Clean exit: leaves immediately without hanging on screen.
hl.curve("vs_exit", {
    type = "bezier",
    points = {
        { 0.40, 0.00 },
        { 1.00, 0.60 },
    },
})

-- Near-continuous swipe curve.
-- One shared curve for both directions prevents the start-stop feeling
-- when rapidly switching through several workspaces.
hl.curve("vs_swipe", {
    type = "bezier",
    points = {
        { 0.25, 0.72 },
        { 0.20, 1.00 },
    },
})

-- Subtle spring for opening and moving windows.
hl.curve("vs_fast", {
    type = "bezier",
    points = {
        { 0.20, 0.78 },
        { 0.28, 1.00 },
    },
})

-- Base fallback
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 1.8,
    bezier = "vs_snap",
})

-- Windows ------------------------------------------------

hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 1.55,
    bezier = "vs_fast",
    style = "popin 96%",
})

hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 1.5,
    bezier = "vs_fast",
    style = "popin 96%",
})

hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1.15,
    bezier = "vs_exit",
    style = "popin 98%",
})

hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 1.35,
    bezier = "vs_fast",
})

-- Opacity and focus changes --------------------------------

hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 1.5,
    bezier = "vs_snap",
})

hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 1.4,
    bezier = "vs_snap",
})

hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 1.1,
    bezier = "vs_exit",
})

hl.animation({
    leaf = "fadeSwitch",
    enabled = true,
    speed = 1.2,
    bezier = "vs_snap",
})

hl.animation({
    leaf = "fadeShadow",
    enabled = true,
    speed = 1.4,
    bezier = "vs_snap",
})

hl.animation({
    leaf = "fadeDim",
    enabled = true,
    speed = 1.4,
    bezier = "vs_snap",
})

hl.animation({
    leaf = "fadePopups",
    enabled = true,
    speed = 1.3,
    bezier = "vs_snap",
})

hl.animation({
    leaf = "fadePopupsOut",
    enabled = true,
    speed = 1.0,
    bezier = "vs_exit",
})

-- Layers: launcher, notifications, overlays ----------------

hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 1.4,
    bezier = "vs_fast",
    style = "fade",
})

hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 1.35,
    bezier = "vs_fast",
    style = "fade",
})

hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 1.0,
    bezier = "vs_exit",
    style = "fade",
})

hl.animation({
    leaf = "fadeLayers",
    enabled = true,
    speed = 1.4,
    bezier = "vs_snap",
})

hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = 1.0,
    bezier = "vs_exit",
})

-- Workspaces -----------------------------------------------
-- Do not split normal workspaces into workspacesIn/Out.
-- Both sides inherit this exact motion, so repeated inputs retarget cleanly
-- and feel like one continuous horizontal swipe sequence.

hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.35,
    bezier = "vs_swipe",
    style = "slidefadevert 26%",
})

-- Scratchpad / special workspace gets its own premium motion.
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 1.5,
    bezier = "vs_fast",
    style = "slidefadevert 16%",
})

hl.animation({
    leaf = "specialWorkspaceOut",
    enabled = true,
    speed = 1.15,
    bezier = "vs_exit",
    style = "slidefadevert 12%",
})

-- Decorations ----------------------------------------------

hl.animation({
    leaf = "border",
    enabled = true,
    speed = 1.3,
    bezier = "vs_fast",
})

hl.animation({
    leaf = "zoomFactor",
    enabled = true,
    speed = 1.5,
    bezier = "vs_fast",
})

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})


-- disable touchpad
hl.device({
    name = "alpsps/2-alps-glidepoint",
    enabled = false,
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Myselfbindings
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd('kitty zsh -c "yazi; exec zsh"'))
hl.bind(mainMod .. " + Z", hl.dsp.exec_cmd('kitty zsh -c "genact; exec zsh"'))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(toggleWaybarCmd))

hl.bind(mainMod .. " + A", hl.dsp.exec_cmd(systemDashboard), {
    description = "Open tiled terminal dashboard",
})


-- Screenshots
hl.bind("Print",
    hl.dsp.exec_cmd("/home/3ty6six7/.local/bin/vs-shot full")
)

hl.bind("SUPER + SHIFT + S",
    hl.dsp.exec_cmd("/home/3ty6six7/.local/bin/vs-shot area")
)

hl.bind("SUPER + SHIFT + Print",
    hl.dsp.exec_cmd("/home/3ty6six7/.local/bin/vs-shot edit")
)

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + D",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

----------------------------------
-----SOME STUFF THAT I ADDED------
----------------------------------

hl.window_rule({
    name = "dolphin-glass",
    match = {
        class = "^(org.kde.dolphin|dolphin)$",
    },

    opacity = "0.92 override 0.86 override 1.0 override",
    xray = true,
    rounding = 10,

    border_color = {
        colors = {
            "rgba(c80000d9)",
            "rgba(ff9600d9)",
        },
        angle = 45,
    },
})

hl.layer_rule({
  match        = { namespace = "launcher" },
  blur         = true,
  ignore_alpha = 0.20,
})

-- Firefox glass, no CSS
hl.window_rule({
  match = { class = "firefox" },
  opacity = "0.90 override 0.84 override 1.0 override",
  xray = true,
})

-- Spotify
hl.window_rule({
    name = "spotify-glass",
    match = {
        class = "Spotify",
    },

    opacity = "0.90 override 0.84 override 1.0 override",
})

-- Dunst Notification
hl.layer_rule({
    name = "dunst-blur",
    match = {
        namespace = "^notifications$",
    },

    blur = true,
    ignore_alpha = 0.15,
})

-- VS Code glass
hl.window_rule({
    name = "vscode-glass",
    match = {
        class = "code-oss",
    },

    opacity = "0.92 override 0.86 override 1.0 override",
    xray = true,
    rounding = 10,

    border_color = {
        colors = {
            "rgba(c80000d9)",
            "rgba(ff9600d9)",
        },
        angle = 45,
    },
})

-- LocalSend glass
hl.window_rule({
    name = "localsend-glass",
    match = {
        class = "localsend",
    },

    opacity = "0.90 override 0.84 override 1.0 override",
    xray = true,
    rounding = 10,

    border_color = {
        colors = {
            "rgba(c80000d9)",
            "rgba(ff9600d9)",
        },
        angle = 45,
    },
})

-- NVIDIA
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

