wallpaper {
    monitor = DP-3
    path = /home/3ty6six7/Pictures/Wallpapers/miyabi-looking-up-at-the-gray-sky-zenless-zone-zero-thumb.jpg
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/3ty6six7/Pictures/Wallpapers/miyabi-looking-up-at-the-gray-sky-zenless-zone-zero-thumb.jpg
}

splash = false
ipc = on
