-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

------------------
---- MONITORS ----
------------------

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@100",
    position = "0x0",
    scale = 1,
    transform = 0
})

---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "fuzzel"

local liveWallpaper =
    "/home/3ty6six7/Pictures/Wallpapers/live/miyabi-looking-up-at-the-gray-sky-zenless-zone-zero-moewalls-com.mp4"

local toggleWaybarCmd = [[
    bash -lc '
        if pgrep -x waybar >/dev/null; then
            pkill -x waybar
        else
            waybar >/tmp/waybar.log 2>&1 &
        fi
    '
]]

local liveWallpaperCmd =
    'mpvpaper ALL "' .. liveWallpaper ..
    '" -o "no-audio loop-file=inf hwdec=auto"'

-- Startup system dashboard
local systemDashboard = [[
    kitty --class sysinfo --title Sysinfo \
        zsh -lc 'clear; fastfetch; echo; ~/.config/hypr/scripts/sysinfo-panel.sh; exec zsh'
]]

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    -- Core session
    hl.exec_cmd("playerctld daemon")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 20")
    hl.exec_cmd("nm-applet")
    -- hl.exec_cmd("fcitx5")

    -- Desktop
    -- hl.exec_cmd(liveWallpaperCmd)
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("waybar")
    hl.exec_cmd("dunst")

    -- System
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("hypridle")

    -- Startup dashboard
    hl.exec_cmd(systemDashboard)
    hl.exec_cmd("sleep 1 && hyprlock")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "20")
hl.env("HYPRCURSOR_SIZE", "20")

-----------------------
----- PERMISSIONS -----
-----------------------

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border = {
                colors = {
                    "rgba(c80000d9)",
                    "rgba(ff9600d9)"
                },
                angle = 45
            },

            inactive_border = "rgba(595959aa)",
        },

        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled  = true,
            size     = 3,
            passes   = 1,
            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-----------------------
------ ANIMATION ------
-----------------------

hl.curve("smooth", {
    type = "bezier",
    points = {
        { 0.20, 0.70 },
        { 0.35, 1.00 },
    },
})

hl.curve("pop", {
    type = "bezier",
    points = {
        { 0.15, 0.45 },
        { 0.30, 1.00 },
    },
})

hl.curve("move", {
    type = "bezier",
    points = {
        { 0.18, 0.50 },
        { 0.32, 1.00 },
    },
})

hl.curve("exit", {
    type = "bezier",
    points = {
        { 0.22, 0.00 },
        { 0.75, 0.55 },
    },
})

hl.curve("workspace", {
    type = "bezier",
    points = {
        { 0.12, 0.45 },
        { 0.22, 1.00 },
    },
})

hl.animation({
    leaf = "global",
    enabled = true,
    speed = 1.25,
    bezier = "smooth",
})

hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 1.75,
    bezier = "pop",
    style = "popin 80%",
})

hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 2.0,
    bezier = "pop",
    style = "popin 70%",
})

hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1,
    bezier = "exit",
    style = "popin 30%",
})

hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 1.75,
    bezier = "move",
})

hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 1.75,
    bezier = "pop",
    style = "popin 70%",
})

hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 1.75,
    bezier = "pop",
    style = "popin 70%",
})

hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 1.00,
    bezier = "exit",
    style = "popin 30%",
})

hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 2.25,
    bezier = "workspace",
    style = "slidefade 10%",
})

hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 2.0,
    bezier = "pop",
    style = "slidefadevert 22%",
})

hl.animation({
    leaf = "specialWorkspaceOut",
    enabled = true,
    speed = 2.0,
    bezier = "exit",
    style = "slidefadevert 12%",
})

hl.animation({
    leaf = "border",
    enabled = true,
    speed = 1.75,
    bezier = "move",
})

hl.animation({
    leaf = "zoomFactor",
    enabled = true,
    speed = 1.75,
    bezier = "move",
})

----------------
---- LAYOUTS ----
----------------

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

hl.config({
    master = {
        new_status = "master",
    },
})

hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
---- MISC ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,
    },
})

---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,
        sensitivity = 0,

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

hl.device({
    name = "alpsps/2-alps-glidepoint",
    enabled = false,
})

hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"

hl.bind(mainMod .. " + X", hl.dsp.exec_cmd(terminal))

local closeWindowBind =
    hl.bind(mainMod .. " + C", hl.dsp.window.close())

hl.bind(
    mainMod .. " + M",
    hl.dsp.exec_cmd(
        "command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"
    )
)

hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))

-- Myselfbindings
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd('kitty zsh -c "yazi; exec zsh"'))
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd('kitty zsh -c "gtop; exec zsh"'))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(toggleWaybarCmd))
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("~/.config/hypr/scripts/sysinfo.sh"))

-- Screenshots
hl.bind(
    "Print",
    hl.dsp.exec_cmd("/home/3ty6six7/.local/bin/vs-shot full")
)

hl.bind(
    "SUPER + S",
    hl.dsp.exec_cmd("/home/3ty6six7/.local/bin/vs-shot area")
)

hl.bind(
    "SUPER + Print",
    hl.dsp.exec_cmd("/home/3ty6six7/.local/bin/vs-shot edit")
)

-- Focus
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Workspaces
for i = 1, 10 do
    local key = i % 10

    hl.bind(
        mainMod .. " + " .. key,
        hl.dsp.focus({ workspace = i })
    )

    hl.bind(
        mainMod .. " + SHIFT + " .. key,
        hl.dsp.window.move({ workspace = i })
    )
end

-- Special workspace
hl.bind(
    mainMod .. " + D",
    hl.dsp.workspace.toggle_special("magic")
)

hl.bind(
    mainMod .. " + SHIFT + D",
    hl.dsp.window.move({ workspace = "special:magic" })
)

-- Scroll workspaces
hl.bind(
    mainMod .. " + mouse_down",
    hl.dsp.focus({ workspace = "e+1" })
)

hl.bind(
    mainMod .. " + mouse_up",
    hl.dsp.focus({ workspace = "e-1" })
)

-- Mouse
hl.bind(
    mainMod .. " + mouse:272",
    hl.dsp.window.drag(),
    { mouse = true }
)

hl.bind(
    mainMod .. " + mouse:273",
    hl.dsp.window.resize(),
    { mouse = true }
)

-- Multimedia
hl.bind(
    "XF86AudioRaiseVolume",
    hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
    { locked = true, repeating = true }
)

hl.bind(
    "XF86AudioLowerVolume",
    hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
    { locked = true, repeating = true }
)

hl.bind(
    "XF86AudioMute",
    hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
    { locked = true, repeating = true }
)

hl.bind(
    "XF86AudioMicMute",
    hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
    { locked = true, repeating = true }
)

hl.bind(
    "XF86MonBrightnessUp",
    hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),
    { locked = true, repeating = true }
)

hl.bind(
    "XF86MonBrightnessDown",
    hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),
    { locked = true, repeating = true }
)

-- Media
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

local suppressMaximizeRule = hl.window_rule({
    name = "suppress-maximize-events",
    match = {
        class = ".*",
    },

    suppress_event = "maximize",
})

hl.window_rule({
    name = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-------------------------
---- WINDOW RULES ----
-------------------------

hl.window_rule({
    name = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },

    move  = "20 monitor_h-120",
    float = true,
})

-- Startup sysinfo dashboard
hl.window_rule({
    name = "sysinfo-float",
    match = {
        class = "^sysinfo$",
    },

    float = true,
    size = "700 700",
    move = "calc(50% - 350) calc(50% - 350)",
})

hl.layer_rule({
    name = "no-anim-for-selection",
    match = {
        namespace = "^selection$",
    },
    no_anim = true,
})

-------------------------
---- GLASS / EFFECTS ----
-------------------------

hl.window_rule({
    name = "dolphin-glass",
    match = {
        class = "^(org.kde.dolphin|dolphin)$",
    },

    opacity = "0.92 override 0.86 override 1.0 override",
    xray = true,
    rounding = 10,

    border_color = {
        colors = {
            "rgba(c80000d9)",
            "rgba(ff9600d9)",
        },
        angle = 45,
    },
})

hl.layer_rule({
    match        = { namespace = "launcher" },
    blur         = true,
    ignore_alpha = 0.20,
})

hl.window_rule({
    match = {
        class = "firefox",
    },

    opacity = "0.90 override 0.84 override 1.0 override",
    xray = true,
})

hl.window_rule({
    name = "spotify-glass",
    match = {
        class = "Spotify",
    },

    opacity = "0.90 override 0.84 override 1.0 override",
})

hl.layer_rule({
    name = "dunst-blur",
    match = {
        namespace = "^notifications$",
    },

    blur = true,
    ignore_alpha = 0.15,
})

hl.window_rule({
    name = "vscode-glass",
    match = {
        class = "code-oss",
    },

    opacity = "0.92 override 0.86 override 1.0 override",
    xray = true,
    rounding = 10,

    border_color = {
        colors = {
            "rgba(c80000d9)",
            "rgba(ff9600d9)",
        },
        angle = 45,
    },
})

hl.window_rule({
    name = "localsend-glass",
    match = {
        class = "localsend",
    },

    opacity = "0.90 override 0.84 override 1.0 override",
    xray = true,
    rounding = 10,

    border_color = {
        colors = {
            "rgba(c80000d9)",
            "rgba(ff9600d9)",
        },
        angle = 45,
    },
})

----------------
---- NVIDIA ----
----------------

hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")